spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jdbcstudy
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      aop-patterns: com.lh.springboot.*

      stat-view-servlet:
        enabled: true
        login-password: admin
        login-username: admin
        resetEnable: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

      filter:
        stat:
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
  redis:
    host: 192.168.126.128
    port: 6379

mybatis:
  mapper-locations: classpath:/mapper/*.xml





